# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp1 <- function(inputn, inputp, inputQ, inputtype) {
    .Call('garchsv_cpp1', PACKAGE = 'garchsv', inputn, inputp, inputQ, inputtype)
}

cpp2 <- function(inputn, inputp, inputQ, inputtype, method) {
    .Call('garchsv_cpp2', PACKAGE = 'garchsv', inputn, inputp, inputQ, inputtype, method)
}

cpp3 <- function(y, maxiter, Nb) {
    .Call('garchsv_cpp3', PACKAGE = 'garchsv', y, maxiter, Nb)
}

cpp4 <- function(y, p, Q, maxiter, Nb) {
    .Call('garchsv_cpp4', PACKAGE = 'garchsv', y, p, Q, maxiter, Nb)
}

cpp5 <- function(y, p, Q, maxiter, Nb) {
    .Call('garchsv_cpp5', PACKAGE = 'garchsv', y, p, Q, maxiter, Nb)
}

cpp6 <- function(y, p, Q, wdp, maxiter, Nb) {
    .Call('garchsv_cpp6', PACKAGE = 'garchsv', y, p, Q, wdp, maxiter, Nb)
}

cpp7 <- function(Macf, Szacf, Snacf, Wacf, psiacf, fiacf, Mu0acf, len, tsize) {
    .Call('garchsv_cpp7', PACKAGE = 'garchsv', Macf, Szacf, Snacf, Wacf, psiacf, fiacf, Mu0acf, len, tsize)
}

fitgarch <- function(y, p, Q, method, maxiter) {
    .Call('garchsv_fitgarch', PACKAGE = 'garchsv', y, p, Q, method, maxiter)
}

simdatag <- function(n, p, Q, method) {
    .Call('garchsv_simdatag', PACKAGE = 'garchsv', n, p, Q, method)
}

cpp8 <- function(A0acf, A1acf, Bacf, Hacf, Szacf, Macf, Muacf, psiacf, tsize) {
    .Call('garchsv_cpp8', PACKAGE = 'garchsv', A0acf, A1acf, Bacf, Hacf, Szacf, Macf, Muacf, psiacf, tsize)
}

BTR0 <- function(predv, check, n2, n, holdstart) {
    .Call('garchsv_BTR0', PACKAGE = 'garchsv', predv, check, n2, n, holdstart)
}

mixsim <- function(n1, n2) {
    .Call('garchsv_mixsim', PACKAGE = 'garchsv', n1, n2)
}

BTR <- function(predv, check, n2, n, holdstart) {
    .Call('garchsv_BTR', PACKAGE = 'garchsv', predv, check, n2, n, holdstart)
}

